### PR TITLE
Added minimum system requirements page for each CoDrone product

### PR DESCRIPTION
**Pull request by dbautista2000**

### CODE REVIEW

**Comment by la-firestone** [comment]
@dbautista2000 
For CDE, I think the sys requirements were already listed inside of the "How to use Blockly" and "Setup and installation" for Python. We should either: 

1. Move out the device requirements and just keep the "Minimum System Requirements" pages (probably preferred)
2. delete the new pages and just move all of the information inside of the sections that already exist

CoDrone Mini and Pro are ok.

**Comment by la-firestone** [comment]
something I also forgot to add was that we should come pu with some better titles other than "setup and installation" for.the Python section. it doesn't match with the Blockly "how to use blockly". Any suggestions?

**Comment by dbautista2000** [comment]
> @dbautista2000 For CDE, I think the sys requirements were already listed inside of the "How to use Blockly" and "Setup and installation" for Python. We should either:
> 
> 1. Move out the device requirements and just keep the "Minimum System Requirements" pages (probably preferred)
> 2. delete the new pages and just move all of the information inside of the sections that already exist
> 
> CoDrone Mini and Pro are ok.

I was thinking maybe we should do option 2. "How to use Blockly" and "Setup and installation" includes extra but useful information about the hardware requirements and mentions that we should make sure to be up-to-date with our setup. We could include the "Minimum System Requirements" inside of those sections but remind them that "for the best experience" update their browser.

**Comment by dbautista2000** [comment]
> something I also forgot to add was that we should come pu with some better titles other than "setup and installation" for.the Python section. it doesn't match with the Blockly "how to use blockly". Any suggestions?

- "How to use Blockly"/"How to use Python"
- "Getting started with Blockly"/"Getting started with Python"
- "Using Blockly Guide"/"Using Python Guide"

I like the 2nd one more

**Comment by la-firestone** [comment]
I like "Getting Started with Blockly/Python" but it might be too long. Try and see how it looks. We can always shorten it to "Getting Started" only for both.

Let's delete the separate section on system requirements and lump it all together with Getting Started

**Review by la-firestone — APPROVED** [review]
I re-formatted the device requirements so the important information was at the top.

**Pull request merged**
